### ISSUE TITLE
is this way still working?

### ISSUE THREAD

**Issue by gezilinll** [icota/clion-rust-android-debug-howto#1]
I have tried so many ways to debug rust on Android (Android Studio、IDEA、VS Code...) but all failed😭

just want to know that is this way can debug rust source code? and can you show how configure CLion remote debug? I have no idea how to run the command at last of your article. 

Thank you very much!

**Comment by icota** [comment]
Hi @LinBinghe I haven't had a need to debug Rust on Android for some time. But perhaps I can help... Where exactly are you stuck?
